import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set(style='ticks')

def drop_and_rename_df(df):
    day_df = df.drop(['instant', 'dteday', 'holiday'], axis=1)

    peta_musim = {1: 'Semi', 2: 'Panas', 3: 'Gugur', 4: 'Dingin'}
    peta_tahun = {0: 2011, 1: 2012}
    peta_cuaca = {1: 'Cerah', 2: 'Berawan', 3: 'Gerimis'}
    peta_bulan = {1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'Mei', 6: 'Jun', 7: 'Jul', 8: 'Agu', 9: 'Sep', 10: 'Okt', 11: 'Nov', 12: 'Des'}
    peta_hari = {0: 'Min', 1: 'Sen', 2: 'Sel', 3: 'Rab', 4: 'Kam', 5: 'Jum', 6: 'Sab'}

    peta_hari_kerja = {0: 'Libur', 1: 'Kerja'}
    day_df['season'] = df['season'].replace(peta_musim)
    day_df['yr'] = df['yr'].replace(peta_tahun)
    day_df['weathersit'] = df['weathersit'].replace(peta_cuaca)
    day_df['mnth'] = df['mnth'].replace(peta_bulan)
    day_df['weekday'] = df['weekday'].replace(peta_hari)
    day_df['workingday'] = df['workingday'].replace(peta_hari_kerja)
    return day_df

def create_hari_df(df):
    hari_df = df.groupby('weekday').agg({
        'casual': 'mean',
        'registered': 'mean',
        'cnt': 'mean'
    }).sort_values(by='weekday').reset_index()
    return hari_df

def create_cuaca_df(df):
    cuaca_df = df.groupby('weathersit', as_index=False).agg({
        'casual': 'mean',
        'registered': 'mean',
        'cnt': 'mean',
    })
    return cuaca_df

def create_musim_df(df):
    musim_df = df.groupby(by=['season'], as_index=False).agg({
        'cnt': 'mean'
    }).sort_values('season', ascending=False)
    return musim_df

def create_musim_dan_cuaca_df(df):
    musim_dan_cuaca_df = df.groupby(by=['season', 'weathersit'], as_index=False).agg({
        'casual': 'mean',
        'registered': 'mean',
        'cnt': 'mean'
    }).sort_values('season', ascending=False)
    return musim_dan_cuaca_df

def regresi_linear(X, Y):
    mean_X = np.mean(X)
    mean_Y = np.mean(Y)

    b = np.sum((X - mean_X) * (Y - mean_Y)) / np.sum((X - mean_X) ** 2)
    a = mean_Y - b * mean_X
    Y_pred = a + b * X
    return Y_pred

with st.sidebar:
    st.write('Nama : Marwan H.')
    st.write(':sparkles:')


day_df = pd.read_csv('Bike-sharing-dataset/day.csv')
day_df = drop_and_rename_df(day_df)
hari_df = create_hari_df(day_df)
cuaca_df = create_cuaca_df(day_df)
musim_df = create_musim_df(day_df)
musim_dan_cuaca_df = create_musim_dan_cuaca_df(day_df)
new_day_df = pd.read_csv('Bike-sharing-dataset/day.csv')
readme = 'Bike-sharing-dataset/Readme.txt'
X = new_day_df['temp']
Y = new_day_df['cnt']
Y_pred = regresi_linear(X, Y)

with open(readme, 'r') as txt:
    readme_content = txt.read()

st.header('Bike Sharing Data Analysis')
st.image('https://bikeshare.rtcsnv.com/wp-content/uploads/2017/12/RTCDock-icon.png')

with st.expander('Dataset Readme'):
    st.write(
        """
        ### Bike Sharing Dataset
        Hadi Fanaee-T
        
        Laboratory of Artificial Intelligence and Decision Support (LIAAD), University of Porto INESC Porto, Campus da FEUP Rua Dr. Roberto Frias, 378 4200 - 465 Porto, Portugal
        
        ### Background 
        Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return 
        back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return 
        back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of 
        over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, 
        environmental and health issues. 
        
        Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by
        these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration
        of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into
        a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important
        events in the city could be detected via monitoring these data.
        
        ### Data Set
        Bike-sharing rental process is highly correlated to the environmental and seasonal settings. For instance, weather conditions,
        precipitation, day of week, season, hour of the day, etc. can affect the rental behaviors. The core data set is related to  
        the two-year historical log corresponding to years 2011 and 2012 from Capital Bikeshare system, Washington D.C., USA which is 
        publicly available in http://capitalbikeshare.com/system-data. We aggregated the data on two hourly and daily basis and then 
        extracted and added the corresponding weather and seasonal information. Weather information are extracted from http://www.freemeteo.com. 
        """
    )

st.subheader('Pertanyaan')

st.markdown(
    """
    1. Pada hari apa jumlah penyewa tertinggi dan terendah?
    2. Bagaimana cuaca mempengaruhi penyewaan sepeda harian?
    3. Bagaimana pengaruh musim terhadap  penyewaan sepeda?
    4. Bagaimana pengaruh cuaca dan kelembapan terhadap  penyewaan sepeda?
    5. Bagaimana pengaruh musim dan cuaca terhadap penyewaan sepeda?
    6. Bagaimana pengaruh suhu terhadap penyewaan sepeda?
    """
)

tab1, tab2, tab3, tab4, tab5, tab6, tab7 = st.tabs(['Q-1','Q-2','Q-3', 'Q-4', 'Q-5', 'Q-6a', 'Q-6b'])

with tab1:
    st.write('Pada hari apa jumlah penyewa tertinggi dan terendah?')
    plt.figure(figsize=(13, 6))
    sns.barplot(data=hari_df, x='weekday', y='cnt', palette='viridis')
    plt.title('Rata-rata penyewaan Sepeda Berdasarkan Hari (2011-2012)', fontsize=18)
    plt.ylabel('')
    plt.xlabel('')
    st.pyplot(plt)

    with st.expander('Kesimpulan'):
        st.write('Penyewa terbanyak adalah hari jumat, bisa jadi karena ada jumatan, meskipun berbeda tipis dari hari kamis. Sementara hari minggu adalah yang terendah.')

with tab2:
    st.write('Bagaimana cuaca mempengaruhi penyewaan sepeda harian?')
    plt.figure(figsize=(13, 5))
    sns.barplot(data=cuaca_df, x='weathersit', y='cnt')
    plt.title('Rata-rata Penyewa Berdasarkan Cuaca', fontsize=18)
    plt.xlabel('')
    plt.ylabel('')
    st.pyplot(plt)

    with st.expander('Kesimpulan'):
        st.write('Pada kondisi cuaca cerah, rata-rata penyewa mencapai puncak, disusul cuaca berawan yang selisihnya tidak terlalu besar. Sedangkan pada cuaca gerimis, penyewa mengalami penurunan yang cukup jauh dari saat kondisi cerah.')

with tab3:
    st.write('Bagaimana pengaruh musim terhadap  penyewaan sepeda?')
    plt.figure(figsize=(12, 7))
    sns.barplot(data=musim_df, x='season', y='cnt')
    plt.title('Pengaruh Musim Pada penyewaan Sepeda', fontsize=20)
    plt.xlabel('')
    plt.ylabel('')
    st.pyplot(plt)

    with st.expander('Kesimpulan'):
        st.write('Musim gugur menjadi musim dengan penyewa terbanyak. Kemudian musim panas dan dingin yang memiliki selisih yang kecil. Lalu yang paling rendah adalah musim semi.')

with tab4:
    st.write('Bagaimana pengaruh cuaca dan kelembapan terhadap  penyewaan sepeda?')
    plt.figure(figsize=(12, 6))
    sns.scatterplot(data=new_day_df, x='hum', y='cnt', hue='weathersit')
    plt.title('Analisis Hubungan Kelembapan dan Cuaca Terhadap penyewaan', fontsize=18)
    plt.legend(title='Cuaca', loc='upper right')
    plt.xlabel('')
    plt.ylabel('')
    st.pyplot(plt)

    with st.expander('Kesimpulan'):
        st.write('Kelembapan dan cuaca memiliki pengaruh kecil terhadap penyewaan sepeda. Namun terlihat ada pola pengelompokan pada plot.')

with tab5:
    st.write('Bagaimana pengaruh musim dan cuaca terhadap penyewaan sepeda?')
    plt.figure(figsize=(13, 7))
    sns.barplot(data=musim_dan_cuaca_df, x='season', y='cnt', hue='weathersit')
    plt.title('Rata-rata Penyewa Setiap Musim Pada Cuaca Tertentu', fontsize=18)
    plt.legend(title='Cuaca', loc='upper left')
    plt.xlabel('')
    plt.ylabel('')
    st.pyplot(plt)

    with st.expander('Kesimpulan'):
        st.write('Musim memiliki pengaruh yang signifikan terhadap jumlah penyewaan yang terlihat pada selilih antara musim gugur dan musim semi yang besar. '
                 'Cuaca juga berpengaruh besar pada penyewaan sepeda. Pada cuaca cerah, jumlah penyewaan sepeda lebih banyak dibandingkan cuca berawan, '
                 'yang kemudian disusul oleh cuaca gerimis. Pada musim tertentu, cuaca akan menjadi lebih ekstrim dari yang biasanya, '
                 'seperti pada cuaca gerimis dimusim panas dan musim gugur. '
                 'Terlihat bahwa penyewaan pada musim panas dicuaca gerimis lebih sedikit daripada cuaca gerimis dimusim gugur.')

with tab6:
    st.write('Bagaimana pengaruh suhu terhadap penyewaan sepeda?')
    plt.figure(figsize=(12, 6))
    sns.scatterplot(data=new_day_df, x='temp', y='cnt')
    plt.title('Analisis Hubungan Kelembapan dan Cuaca Terhadap penyewaan', fontsize=18)
    plt.xlabel('')
    plt.ylabel('')
    st.pyplot(plt)

    st.write('Menjelaskan hubungan dengan regresi linear')
    st.write('Persamaan Regresi Linear Sederhana: ')
    st.latex("""
            Y = a + bX
    """)
    st.write('Rumus Koefisien Regresi (Slope) dalam Metode OLS: ')
    st.latex(r"""
        b = \frac{\sum_{i=1}^{n} (X_i - \bar{X})(Y_i - \bar{Y})}{\sum_{i=1}^{n} (X_i - \bar{X})^2}
    """)
    st.write('Rumus Intercept dalam Metode OLS: ')
    st.latex(r"""
            a = \bar{Y} - b \bar{X}
    """)

    with st.expander('Penjelasan rumus: '):
        st.write(r"""
            $Y$ adalah variabel dependen (jumlah penyewaan sepeda). 
            
            $X$ adalah variabel independen (suhu).
            
            $a$ adalah intercept (titik potong dengan sumbu Y).
            
            $b$ adalah koefisien regresi (slope).
            
            $\bar{X}$ adalah rata-rata dari variabel independen.
            
            $\bar{Y}$ adalah rata-rata dari variabel dependen.
        
            $n$ adalah jumlah data observasi.
        """)


with tab7:
    st.write('Berikut hasil regresi linear')
    fig, ax = plt.subplots(figsize=(12, 6))
    ax.scatter(X, Y)
    ax.plot(X, Y_pred, color='red', label='Regresi Linear')
    ax.set_title('Regresi Linear Antara Suhu dan Jumlah Penyewaan Sepeda', fontsize=18)
    ax.set_ylabel('')
    ax.set_xlabel('')
    ax.legend()
    st.pyplot(plt)

    with st.expander('Kesimpulan'):
        st.write('Suhu sebagai variabel independen dan jumlah penyewa sepeda sebagai variabel dependen memiliki hubungan linier meskipun tidak besar dan masih banyak faktor yang mempengaruhi.')



st.caption('(c) Copyright 2023')